### ISSUE TITLE
CTC 125.55 without LPPC_CTR and with LPPT_GND on

### ISSUE THREAD

**Issue by becas22** [pedro2555/messagemaker#67]
LPPT ATIS J 1330 EXP ILS APCH RWY IN USE 21 TL 55
ON THE GROUND CONTACT 125.55 AFTER LANDING VACATE VIA HS
MEDIUM AND LGT AIRCRAFT EXP POSITION U FOR DEP TKOF AVBL DIST 2410 M IF UNABLE ADVISE BEFORE TAX
WND 130 DEG 7 KT VRB BTN 100 AND 160 DEG FBL RA VIS 6 KM CLD
SCT 700 FT FEW CB 2000 FT BKN 3400 FT TEMP 10 DP 9 QNH 1008
COMPLY WITH SPEED LIMITATIONS UNLESS OTHERWISE ADVISED BY ATC
ACK LPPT INFO J

Online Stations: LPPT_T_GND and LPPT_M_GND

**Comment by pedro2555** [comment]
ok, will check

**Comment by pedro2555** [comment]
This seems to be an issue with the project that collects vatsim data. I'll have that check on that side.

**Comment by pedro2555** [comment]
At this point I have to assume this is not confirmable. The most likelly cause for this, is using outdated information from VATSIM. The service used to fecth VATSIM controllers acts as a cache, providing the latest information available from VATSIM. What this means is if  the service cannot reach VATSIM, for one reason or another, the latest, cached response, is returned.

The course of action at the moment, is to deprecate the usage of the current service, and call VATSIM directly. This is mostly due to wake up time of Heroku workers (the current server provider for this application and the VATSIM service), reducing the amount of workers that need to wake up to just one, this one; as opposed to two, this one and the VATSIM one.

#71 should allow work to start on that front.

If the assumptions are correct, that will solve this issue.

**Comment by pedro2555** [comment]
confirmed to be an issue in https://github.com/pedro2555/vatsim-api
